from enum import StrEnum


class UserRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    SELLER = "SELLER"
    COMPANY = "COMPANY"
    ADMIN = "ADMIN"
    SUB_ADMIN = "SUB_ADMIN"


class SimStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    KYC_PENDING = "KYC_PENDING"
    KYC_VERIFIED = "KYC_VERIFIED"
    KYC_CORRECTION_REQUESTED = "KYC_CORRECTION_REQUESTED"
    KYC_REJECTED = "KYC_REJECTED"
    ACTIVATING = "ACTIVATING"
    ACTIVE = "ACTIVE"
    ACTIVE_IN_USE = "ACTIVE_IN_USE"
    ACTIVE_IDLE = "ACTIVE_IDLE"
    DORMANT = "DORMANT"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    FAILED = "FAILED"
    REPLACED = "REPLACED"
    SUSPENDED = "SUSPENDED"
    DEACTIVATION_REQUESTED = "DEACTIVATION_REQUESTED"
    DEACTIVATED = "DEACTIVATED"
    EXPIRED = "EXPIRED"
    PORT_OUT_REQUESTED = "PORT_OUT_REQUESTED"
    PORTED_OUT = "PORTED_OUT"


class KycStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CORRECTION_REQUESTED = "CORRECTION_REQUESTED"


class ActivationStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class ActivationNode(StrEnum):
    HSS_HLR = "HSS_HLR"
    PCRF_PCF = "PCRF_PCF"
    OCS_BILLING = "OCS_BILLING"
    SIM_PROVISIONING = "SIM_PROVISIONING"
    NOTIFICATION = "NOTIFICATION"


class WorkflowNodeStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class ComplaintStatus(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ReplacementStatus(StrEnum):
    REQUESTED = "REQUESTED"
    VERIFIED = "VERIFIED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
